### ISSUE TITLE
Export missing Data

### ISSUE THREAD

**Issue by trineon89** [ForsakenNGS/LogTracker#4]
Hi,

I just checked the Data (LogTracker_CharacterData_EU_5021.lua) and was wondering, why there are only ~100 Characters in the Export? Is there a way to tune the Warcraftlogs Export, API-bound? For a Raidlead, it is hard to get the right ppl to fill in the Spot using this Addon, but without Data it is worthless.

Thanks,

**Comment by ForsakenNGS** [comment]
I unfortunally lost the Database due to a severe Hardware-Issue on my Server and had to start over. (I think it was the day before you reported this) So the state you saw is certainly not representative of the usual quality. Usually every report is scanned and the new character rakings are updated about 12-24 hours later.
