### ISSUE TITLE
old/missing log data & tooltip misalignment

### ISSUE THREAD

**Issue by xyndail** [ForsakenNGS/LogTracker#9]
Great addon idea - having a few issues though with the wrath classic version
1. Tooltip is misaligned, the parse numbers on the right are shifted one row down. 'Last updated' row is blank.
2. Log data is outdated/missing - even with most current characterdata downloaded, I've attached my actual current logs as an example. My logged VoA kill is missing in the tooltip
![Untitled](https://user-images.githubusercontent.com/118672939/202907466-0759cd71-d521-4720-b5be-32ecc2cd112e.png)
![Untitled2](https://user-images.githubusercontent.com/118672939/202907467-10e97d65-9bd4-43f3-8269-db0192ea7b46.png)

**Comment by ForsakenNGS** [comment]
1. Is caused by another addon. I had that issue as well and could not solve it from my side. Unfortunally I don't remember what exact addon caused the issue, but it certainly had the option to disable the offending tooltip enhancement and was not a critical function.

2. Can you tell me your character / region / realm? Then I'll check it for your concrete example.

**Comment by xyndail** [comment]
I've tried it with all addons disabled but yours, it still shows up that way, unfortunately.

Xynn on Grobbulus - US

edit - it was the addon tacotip! just tried a fresh re-install of all of my addons and now disabling tacotip re-aligns the numbers. sorry for the confusion.

**Comment by ForsakenNGS** [comment]
I checked the database and currently my quota for the warcraftlogs-api can't keep up with the number of logs/updates. I've got a region-based queue priority which before was sufficient to keep everything except China up to date, but it seems the load has increased by time and resulted in quite a backlog for US-Servers as well. I'll check for a further increase efficiency and implement some kind of escalation to ensure if a character is in queue for an update for more than e.g. 2 days it's priority is inreased.

> it was the addon tacotip! just tried a fresh re-install of all of my addons and now disabling tacotip re-aligns the numbers. sorry for the confusion.

No worries. I'm pretty sure it was not tacotip itself causing the issue, but a interaction between tacotip and a third addon. I still use tacotip and don't have the issue anymore. For now have go to sleep since it's past 3AM here, but I'll see if I can figure out what exactly I had to change in order to fix the issue.

**Comment by xyndail** [comment]
I tried with all addons except tacotip and logtracker disabled, same issue. evidence points to tacotip - I found the fix for the misalignment. in AddOns -> TacoTip options, the 'Guild Name' box must be checked. if unchecked, the numbers column drops a row.

**Comment by xyndail** [comment]
> I checked the database and currently my quota for the warcraftlogs-api can't keep up with the number of logs/updates. I've got a region-based queue priority which before was sufficient to keep everything except China up to date, but it seems the load has increased by time and resulted in quite a backlog for US-Servers as well. I'll check for a further increase efficiency and implement some kind of escalation to ensure if a character is in queue for an update for more than e.g. 2 days it's priority is inreased.

This sounds great, thank you!

**Comment by ForsakenNGS** [comment]
I've made some improvements and implemented a priority escalation for outdated entries. It will take a few days until the backlog is finished (estimates on the current rate is 3-4 days to finish all pending update for US-Servers), but after that it should stay more consistent in it's update cycle. I might have to adjust the numbers a bit to prevent chinese logs from clogging the update cycle too much. (There's just too many chinese players :D )

I'll leave the issue open until I can confirm it as resolved.

**Comment by ForsakenNGS** [comment]
> Tooltip is misaligned, the parse numbers on the right are shifted one row down. 'Last updated' row is blank.

I checked my installed (and disabled) addons for any tooltip-settings, but unfortunally didn't find any. Probably I uninstalled the addon causing the issue completely. If you could post a screenshot of the full tooltip, maybe I can spot the issue. Otherwise I'd recommend disabling all other addons and then enabling them one-by-one until the issue appears.

**Comment by xyndail** [comment]
> > Tooltip is misaligned, the parse numbers on the right are shifted one row down. 'Last updated' row is blank.
> 
> I checked my installed (and disabled) addons for any tooltip-settings, but unfortunally didn't find any. Probably I uninstalled the addon causing the issue completely. If you could post a screenshot of the full tooltip, maybe I can spot the issue. Otherwise I'd recommend disabling all other addons and then enabling them one-by-one until the issue appears.

I posted a fix a few comments up =)

> I tried with all addons except tacotip and logtracker disabled, same issue. evidence points to tacotip - I found the fix for the misalignment. in AddOns -> TacoTip options, the 'Guild Name' box must be checked. if unchecked, the numbers column drops a row.

**Comment by ForsakenNGS** [comment]
> I posted a fix a few comments up =)

Ah, I must've read over it. Thanks for sharing. I'll check if I can detect and warn about it in chat to make it easier for others.

**Comment by ForsakenNGS** [comment]
Well, that was easy. With the next update (should be live in a few minutes) the Addon will warn you about the issue if you have TacoTip installed and the guild name disabled :)

**Comment by xyndail** [comment]
> I tried with all addons except tacotip and logtracker disabled, same issue. evidence points to tacotip - I found the fix for the misalignment. in AddOns -> TacoTip options, the 'Guild Name' box must be checked. if unchecked, the numbers column drops a row.



> Well, that was easy. With the next update (should be live in a few minutes) the Addon will warn you about the issue if you have TacoTip installed and the guild name disabled :)

Great, thank you. I'll keep you posted on the log update cycle

**Comment by xyndail** [comment]
Most of my logs updated, except for Archavon, strangely. Thank you! Having an issue with the 'average parses' for my 25man's showing much lower than they should be
![Untitled](https://user-images.githubusercontent.com/118672939/204018345-87d166a9-1711-441d-a963-4c4ceb0037cd.png)

**Comment by Buddylee007** [comment]
> 1. Is caused by another addon. I had that issue as well and could not solve it from my side. Unfortunally I don't remember what exact addon caused the issue, but it certainly had the option to disable the offending tooltip enhancement and was not a critical function.
> 
>     2. Can you tell me your character / region / realm? Then I'll check it for your concrete example.

Character is named Buddyjustice / US / Faerlina for example. You can see even on the latest data it shows from October. I see that on several Faerlina characters around town just shift clicking names.
![image](https://user-images.githubusercontent.com/113468285/204395218-0d6c362e-3760-4d74-a25d-f8acee8c1756.png)

**Comment by dumbminican** [comment]
im having a similar issue where on my rogue i get no data whatsoever but i do on my shadow priest. 
![image](https://user-images.githubusercontent.com/38415694/205480516-e6e8dedc-ff0a-4e35-91e2-2d381611c359.png)
